///////////////////////////////////////////////////////////
//  Application.cs
//  Implementation of the Class Application
//  Generated by Enterprise Architect
//  Created on:      02-Jan-2021 4:53:24 AM
//  Original author: ahmad
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using SRAD_System.DLL.DataSradTableAdapters;
using System.Data;

public interface Application {
    /// 
    /// <param name="id"></param>
    string Name { get; set; }
    string email { get; set; }
    string address { get; set; }
    string telNo { get; set; }
    int IC { get; set; }
    bool isdraft { get; set; }
    string type { get;}
    DateTime SubmitDate { get; set; }
    int ApplicationID { get; set; }
    int SRADStaffID { get; set; }
    int FacAddmissionStaffID { get; set; }
    int AppEvaluationStatusID { get; set; }
    void AddApplication(string Name, string email, string address, string telNo, int IC, bool isdraft, DateTime SubmitDate, int ApplicationID,int SRADStaffID,int FacAddmissionStaffID, int AppEvaluationStatusID);
	bool retrieveApplication(int id);
    String AdmissionCategory(int id);
	
}//end Application