///////////////////////////////////////////////////////////
//  Faculty admission department staff.cs
//  Implementation of the Class Faculty admission department staff
//  Generated by Enterprise Architect
//  Created on:      02-Jan-2021 4:53:24 AM
//  Original author: ahmad
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using SRAD_System.DLL.DataSradTableAdapters;
using System.Data;

public class FacultyAdmissionDepartmentStaff {

	private string email;
	private string facultyName;
	private string name;
	private int staffID;
	private string telNo;
	private Application m_Application;

	public FacultyAdmissionDepartmentStaff(){

	}

	~FacultyAdmissionDepartmentStaff(){

	}

	public void getFacInformation(int id)
    {
		FacultyAdmissionDepartmentStaffTableAdapter facc = new FacultyAdmissionDepartmentStaffTableAdapter();
		DataTable table = facc.GetDataByApplication(id);
		email = table.Rows[0][facc.GetData().EmailColumn.Ordinal].ToString();
		facultyName = table.Rows[0][facc.GetData().EmailColumn.Ordinal].ToString();
		name = table.Rows[0][facc.GetData().NameColumn.Ordinal].ToString();
		staffID = (int)table.Rows[0][facc.GetData().StaffidColumn.Ordinal];
		telNo = table.Rows[0][facc.GetData().TelnoColumn.Ordinal].ToString();
	}



}//end Faculty admission department staff