///////////////////////////////////////////////////////////
//  Prospective agent application.cs
//  Implementation of the Class Prospective agent application
//  Generated by Enterprise Architect
//  Created on:      02-Jan-2021 4:53:24 AM
//  Original author: ahmad
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ProspectiveAgentApplication : Agent {

	private string applicationFormFileName;
	private string companyProfile;
	private int ProspectiveAgentApplicationID;

	

}//end Prospective agent application