///////////////////////////////////////////////////////////
//  Prospective student application.cs
//  Implementation of the Class Prospective student application
//  Generated by Enterprise Architect
//  Created on:      02-Jan-2021 4:53:24 AM
//  Original author: ahmad
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using SRAD_System.DLL.DataSradTableAdapters;
using System.Data;
using SRAD_System.BLL;

public class ProspectiveStudentApplication : Student{

	private string applicationFormFileName;
	private string IC_imageFileName;
	private string intakeCategory;
	private string passport_imageFileName;
	private string photoFileName;
	private string qualificationDocumentName;
	private string sponsorLetterFileName;
	private int agentID;

	public ProspectiveStudentApplication()
    {
		ProspectiveStudentApplicationTableAdapter student = new ProspectiveStudentApplicationTableAdapter();
		DataTable table = student.GetByApplicationID(ApplicationID);
		applicationFormFileName = table.Rows[0][student.GetData().ApplicationformfilenameColumn.Ordinal].ToString();
		IC_imageFileName = table.Rows[0][student.GetData().Ic_imagefilenameColumn.Ordinal].ToString();
		intakeCategory = table.Rows[0][student.GetData().IntakecategoryColumn.Ordinal].ToString();
		passport_imageFileName = table.Rows[0][student.GetData().Passport_imagefilenameColumn.Ordinal].ToString();
		photoFileName = table.Rows[0][student.GetData().PhotofilenameColumn.Ordinal].ToString();
		qualificationDocumentName = table.Rows[0][student.GetData().QualificationdocumentnameColumn.Ordinal].ToString();
		sponsorLetterFileName = table.Rows[0][student.GetData().SponsorletterfilenameColumn.Ordinal].ToString();
		//agentID = table.Rows[0][studnet]
    }

}//end Prospective student application