///////////////////////////////////////////////////////////
//  SRAD Staff.cs
//  Implementation of the Class SRAD Staff
//  Generated by Enterprise Architect
//  Created on:      02-Jan-2021 4:53:24 AM
//  Original author: ahmad
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using SRAD_System.DLL.DataSradTableAdapters;
using System.Data;

public class SRADStaff {

	private string email;
	private string name;
	private int staffID;
	private string telNo;
	private Application m_Application;

	public SRADStaff(){
		email = "syahir@yahoo.com";
		name = "babludas";
		staffID = 6;
		telNo = "1234567890";
	}

	~SRADStaff(){

	}

	public void setSRADStaff(Application yolo)
    {
		m_Application = yolo;
	}

	public void AddApplicant(string Name, string email, string address, string telNo, int IC, bool isdraft, DateTime SubmitDate, int ApplicationID, int FacAddmissionStaffID, int AppEvaluationStatusID)
    {
		m_Application.AddApplication(Name, email, address, telNo, IC, isdraft, SubmitDate, ApplicationID, staffID, FacAddmissionStaffID, AppEvaluationStatusID);
    }

}//end SRAD Staff