///////////////////////////////////////////////////////////
//  Agent.cs
//  Implementation of the Class Agent
//  Generated by Enterprise Architect
//  Created on:      02-Jan-2021 4:53:24 AM
//  Original author: ahmad
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Agent {

	private string email;
	private int id;
	private Date joinDate;
	private string name;
	private string telephone;
	private double yearlyKPI;
	private Prospective student application m_Prospective student application;

	public Agent(){

	}

	~Agent(){

	}

	/// 
	/// <param name="message"></param>
	public void display(string message){

	}

	public Prospective student application Prospective student application{
		get{
			return m_Prospective student application;
		}
		set{
			m_Prospective student application = value;
		}
	}

}//end Agent