///////////////////////////////////////////////////////////
//  Application Evaluation Status.cs
//  Implementation of the Class Application Evaluation Status
//  Generated by Enterprise Architect
//  Created on:      02-Jan-2021 4:53:24 AM
//  Original author: ahmad
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Application Evaluation Status {

	private bool approvedBYFaculty;
	private bool approvedBySRAD;
	private Date facultyReviewStartDate;
	private string logFileName;
	private Date reviewDueDate;
	private Date sradEvaluationStartDate;

	public Application Evaluation Status(){

	}

	~Application Evaluation Status(){

	}

	public void acceptOffer(){

	}

	/// 
	/// <param name="agentID"></param>
	public void getList(int agentID){

	}

	/// 
	/// <param name="id"></param>
	public void getLog(int id){

	}

	/// 
	/// <param name="id"></param>
	public void getStatus(int id){

	}

	public void rejectOrder(){

	}

	/// 
	/// <param name="applicantID"></param>
	public void selection(int applicantID){

	}

	public void sendList(){

	}

	public void sendOfferLetter(){

	}

	public void sendStatus(){

	}

	public void storeData(){

	}

	/// 
	/// <param name="ID"></param>
	public void storeStatus(int ID){

	}

}//end Application Evaluation Status