///////////////////////////////////////////////////////////
//  Application.cs
//  Implementation of the Class Application
//  Generated by Enterprise Architect
//  Created on:      02-Jan-2021 4:53:24 AM
//  Original author: ahmad
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Application {

	private string applicantAddress;
	private string applicantEmail;
	private string applicantName;
	private string applicantTelNo;
	private int id;
	private bool isDraft;
	private Date submitDate;
	private string type;
	private Application Evaluation Status m_Application Evaluation Status;

	public Application(){

	}

	~Application(){

	}

	public Application Evaluation Status Application Evaluation Status{
		get{
			return m_Application Evaluation Status;
		}
		set{
			m_Application Evaluation Status = value;
		}
	}

	/// 
	/// <param name="id"></param>
	public void chooseApplicant(int id){

	}

	/// 
	/// <param name="ID"></param>
	public void chooseProspectiveStudent(int ID){

	}

	/// 
	/// <param name="decision"></param>
	public void decision(string decision){

	}

	/// 
	/// <param name="message"></param>
	public void get(string message){

	}

	public void getApplicationList(){

	}

	/// 
	/// <param name="ID"></param>
	public void getDocuments(int ID){

	}

	public void noData(){

	}

	/// 
	/// <param name="message"></param>
	public void send(string message){

	}

	public void sendData(){

	}

	public void showApplication(){

	}

	public void storeLog(){

	}

	public void updateStatus(){

	}

	/// 
	/// <param name="message"></param>
	public void updateStatus(string message){

	}

}//end Application