///////////////////////////////////////////////////////////
//  Prospective student application.cs
//  Implementation of the Class Prospective student application
//  Generated by Enterprise Architect
//  Created on:      02-Jan-2021 4:53:24 AM
//  Original author: ahmad
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Prospective student application : Application {

	private string applicationFormFileName;
	private string IC_imageFileName;
	private string intakeCategory;
	private string passport_imageFileName;
	private string photoFileName;
	private string qualificationDocumentName;
	private string sponsorLetterFileName;

	public Prospective student application(){

	}

	~Prospective student application(){

	}

	/// 
	/// <param name="course"></param>
	public void choose(string course){

	}

	private void forbidden(){

	}

	public void getData(){

	}

	/// 
	/// <param name="message"></param>
	public void getData(string message){

	}

	/// 
	/// <param name="message"></param>
	public void input(string message){

	}

	public void invalidMsg(){

	}

	/// 
	/// <param name="amount"></param>
	public void makePayment(double amount){

	}

	public void saveFrom(){

	}

	public void showForm(){

	}

	public void submit(){

	}

	public void success(){

	}

	/// 
	/// <param name="document"></param>
	public void upload(string document){

	}

}//end Prospective student application