///////////////////////////////////////////////////////////
//  Prospective agent application.cs
//  Implementation of the Class Prospective agent application
//  Generated by Enterprise Architect
//  Created on:      02-Jan-2021 4:53:24 AM
//  Original author: ahmad
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Prospective agent application : Application {

	private string applicationFormFileName;
	private string companyProfile;

	public Prospective agent application(){

	}

	~Prospective agent application(){

	}

	public void getData(){

	}

	/// 
	/// <param name="message"></param>
	public void input(string message){

	}

	public void invalidMsg(){

	}

	public void showForm(){

	}

	public void submit(){

	}

	public void success(){

	}

}//end Prospective agent application