///////////////////////////////////////////////////////////
//  SRAD Staff.cs
//  Implementation of the Class SRAD Staff
//  Generated by Enterprise Architect
//  Created on:      02-Jan-2021 4:53:24 AM
//  Original author: ahmad
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class SRAD Staff {

	private string email;
	private string name;
	private int staffID;
	private string telNo;
	private Application m_Application;

	public SRAD Staff(){

	}

	~SRAD Staff(){

	}

	public Application Application{
		get{
			return m_Application;
		}
		set{
			m_Application = value;
		}
	}

	/// 
	/// <param name="decision"></param>
	public void decision(string decision){

	}

	/// 
	/// <param name="message"></param>
	public void display(string message){

	}

	/// 
	/// <param name="form"></param>
	/// <param name="company"></param>
	public void display(string form, string company){

	}

	public void displayAdmissionStatistic(){

	}

	public void displayFacultyReviewLog(){

	}

	public void displayNameList(){

	}

	/// 
	/// <param name="message"></param>
	public void displayResult(string message){

	}

	public void displayStatisitic(){

	}

	/// 
	/// <param name="message"></param>
	public void message(string message){

	}

	/// 
	/// <param name="prospectiveStudentList"></param>
	public void show(Application prospectiveStudentList){

	}

}//end SRAD Staff